### PR TITLE
Remove installation of web server index files

### PR DESCRIPTION
**Pull request by tescande**
This is intended to be done by the xo-lite package.

### CODE REVIEW

**Review by ydirson — APPROVED** [review]

**Comment by stormi** [comment]
The changelog entry is missing

**Comment by stormi** [comment]
The tarball was created before the source PR was merged, but nothing changed on master branch so we're good.

**Review by stormi — APPROVED** [review]

**Comment by stormi** [comment]
We'll merge once activity in koji can start again. By then we'll likely have to rebase this PR on an updated xcp-ng-release (both tarball and spec file).

**Comment by stormi** [comment]
I rebased on latest master, incremented the Release tag, and rebuilt the tarball.

**Comment by stormi** [comment]
Koji build (v8.3-incoming): http://koji.xcp-ng.org/taskinfo?taskID=37811

**Pull request merged**
